language: bash

services:
  - docker

before_install:
  - export PATH=$PATH:$HOME/.local/bin
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin 

install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build --no-cache -t uvarc/hugo-build:v2 . || exit 1;
    docker push uvarc/hugo-build:v2 || exit 1;
    fi

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - nem2p@virginia.edu
