name: Docker Build CI

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker container
        run: docker build --no-cache -t uvarc/hugo-build:v2 .
      - name: Push Docker container
        run: docker push uvarc/hugo-build:v2
